spring:
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: zipkin:9411
  application:
    name: gateway-server
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8071/}

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG
