management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
