version: '3.9'
services:
  database:
    container_name: database
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root123"
      PGPASSWORD: "root123"
      POSTGRES_DB:       "ostock_dev"
      PGPORT: 5433
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    container_name: configserver
    image: rquispe/config-server:1.0-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    container_name: eurekaserver
    image: rquispe/eureka-server:1.0-SNAPSHOT
    ports:
      - "8070:8070"
    environment:
      CONFIG_SERVER_URI: "http://configserver:8071/"
      EUREKA_SERVER_URI: "http://eurekaserver:8070/eureka/"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"
  gatewayserver:
    container_name: gatewayserver
    image: rquispe/gateway-server:1.0-SNAPSHOT
    ports:
      - "8072:8072"
    environment:
      CONFIG_SERVER_URI: "http://configserver:8071/"
      EUREKA_SERVER_URI: "http://eurekaserver:8070/eureka/"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway"
#  keycloak:
#    image: jboss/keycloak
#    restart: always
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#    ports:
#      - "8080:8080"
#    networks:
#      backend:
#        aliases:
#          - "keycloak"
  licensingservice:
    container_name: licensingservice
    image: rquispe/licensing-service:1.0-SNAPSHOT
    environment:
      CONFIG_SERVER_URI: "http://configserver:8071/"
      EUREKA_SERVER_URI: "http://eurekaserver:8070/eureka/"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5433/ostock_dev"
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8180:8080"
    networks:
      - backend
  organizationservice:
    container_name: organizationservice
    image: rquispe/organization-service:1.0-SNAPSHOT
    environment:
      CONFIG_SERVER_URI: "http://configserver:8071/"
      EUREKA_SERVER_URI: "http://eurekaserver:8070/eureka/"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5433/ostock_dev"
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge
