version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      backend:
        aliases:
          - "zookeeper"
  kafkaserver:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafkaserver
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: dresses:1:1,ratings:1:1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      backend:
        aliases:
          - "kafka"
  redisserver:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      backend:
        aliases:
          - "redis"
  database:
    container_name: database
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root123"
      PGPASSWORD: "root123"
      POSTGRES_DB:       "ostock_dev"
      PGPORT: 5433
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    container_name: configserver
    image: rquispe/config-server:1.0-SNAPSHOT
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    container_name: eurekaserver
    image: rquispe/eureka-server:1.0-SNAPSHOT
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
    ports:
      - "8070:8070"
    environment:
      CONFIG_SERVER_URI: "http://configserver:8071/"
      EUREKA_SERVER_URI: "http://eurekaserver:8070/eureka/"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"
  gatewayserver:
    container_name: gatewayserver
    image: rquispe/gateway-server:1.0-SNAPSHOT
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
    ports:
      - "8072:8072"
    environment:
      CONFIG_SERVER_URI: "http://configserver:8071/"
      EUREKA_SERVER_URI: "http://eurekaserver:8070/eureka/"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway"
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - "keycloak"
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
  licensingservice:
    container_name: licensingservice
    image: rquispe/licensing-service:1.0-SNAPSHOT
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
    environment:
      CONFIG_SERVER_URI: "http://configserver:8071/"
      EUREKA_SERVER_URI: "http://eurekaserver:8070/eureka/"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5433/ostock_dev"
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8180:8080"
    networks:
      - backend
  organizationservice:
    container_name: organizationservice
    image: rquispe/organization-service:1.0-SNAPSHOT
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
    environment:
      CONFIG_SERVER_URI: "http://configserver:8071/"
      EUREKA_SERVER_URI: "http://eurekaserver:8070/eureka/"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5433/ostock_dev"
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge
