spring:
  application:
    name: organization-service
  profiles:
    active: dev
  #    Spring Boot 2.4 introduced a new way to import configuration data via the spring.config.import property.
  #  This is now the default way to bind to Config Server.
  config:
    import: configserver:http://localhost:8071/

server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
