spring:
  application:
    name: organization-service
  profiles:
    active: dev
  #    Spring Boot 2.4 introduced a new way to import configuration data via the spring.config.import property.
  #  This is now the default way to bind to Config Server.
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8071/}
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
#          Provides (hints) the message type that’s sent and received (in this case, JSON)
          contentType: application/json
#      bindings:
#        publishOrganizationChange-out-0:
#          destination: orgChangeTopic
      kafka:
        binder:
#          These properties provide the network location of Kafka and Zookeeper.
          zkNodes: localhost
          brokers:
            - localhost:9092


server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka/
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

#keycloak:
#  realm: spmia-realm
#  auth-server-url: http://localhost:8080
#  ssl-required: external
#  use-resource-role-mappings: true
#  bearer-only: true
#  resource: ostock
#  credentials.secret: IQdLisO94wrct7cnHaFIwQbguznltLNc

