#It is vital to name all of the services that we are going to
#create in our archi- tecture for service discovery
spring:
  application:
    name: config-server
  profiles:
    active:
      - vault
  cloud:
    config:
      server:
        vault:
          port: 8200
          host: 127.0.0.1
          kvVersion: 2
          backend: secrets
          default-key: application
          skip-ssl-validation: true
          kv-version: 2
          scheme: http
#port where config server will listen in on, in order to provide
#  the requested configuration data.
server:
  port: 8071

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"
