#It is vital to name all of the services that we are going to
#create in our archi- tecture for service discovery
spring:
  application:
    name: config-server
  profiles:
    active:
      - native, git
  cloud:
    config:
      server:
        git:
          skip-ssl-validation: true
          default-label: master
          uri: https://github.com/rquispem/cloud-config.git
#          Tells Spring Cloud Config what path in Git to use to look for the config files
          searchPaths: licensingservice
#port where config server will listen in on, in order to provide
#  the requested configuration data.
server:
  port: 8071

encrypt:
  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"
