spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8070
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
    expected-client-renewal-interval-seconds: 15


management:
  endpoints:
    web:
      exposure:
        include: "*"
